name: Build and Deploy
on:
  push:
    paths:
      - 'portfolio/**'
      - '.github/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        cd portfolio
        npm install
        npm run-script build
        touch build/.nojekyll

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.0.5
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: portfolio/build # The folder the action should deploy.
